# Name of the site (displayed in the header)
name: Zoltan Altfatter

# Short bio or description (displayed in the header)
description: Software Engineer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/1025546?v=3&s=460

#
# Flags below are optional
#

include: [.well-known, _pages]

paginate: 6
paginate_path: /page:num/

# Includes an icon in the footer for each username you enter
footer-links:
  email: altfatterz@gmail.com
  github: altfatterz
  linkedin: zoltanaltfatter
  rss: rss
  twitter: altfatterz

disqus: zoltanaltfatter

google_analytics: UA-74990725-1

url: http://zoltanaltfatter.com

baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink:            pretty

markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  style: :compressed # expanded or compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
